# -*- coding: utf-8 -*-
"""Navya_4AL17EC060

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGWcUVxMB5aT_ST3aFVyh6kNpzh5kcv6
"""

attempt=0
while attempt<3:
  user_name=input("Enter the username:")
  password=input("Enter the password:")
  if user_name=="Micheal" and password=="e3$WT89x":
      print("You have successfully logged in")
  else:
      attempt+=1
      print("Invalid username or password")
      if attempt==3:
         print("Account locked")
        
        # After login, again it is asking for credentials, Fix the bug
        Enter the username:Micheal
Micheal
Enter the password:e3$WT89x
e3$WT89x
You have successfully logged in
Enter the username:sd
sd
Enter the password:
